# This workflow is largely based on
# https://github.com/salsify/ember-css-modules/blob/master/.github/workflows/ci.yml

name: PR

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  workflow_dispatch:
  pull_request:

env:
  CI: true

jobs:
  test-locked-deps:
    name: Locked Deps
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint JS
        run: yarn lint:js
      - name: Lint Types
        run: yarn lint:types
      - name: Lint Handlebars
        run: yarn lint:hbs
      - name: Browser Tests
        run: yarn test:ember

  test-old-dependencies:
    name: Oldest Supported Env
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Browser Tests
        run: yarn test:ember

  test-try:
    name: Ember Try
    runs-on: ubuntu-20.04
    needs: [test-locked-deps]
    strategy:
      matrix:
        scenario:
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-4.0.0
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Try Scenario
        run: yarn ember try:one ${{ matrix.scenario }}
