name: PR

on:
  workflow_dispatch:
  pull_request:

env:
  CI: true

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup
  #       uses: wyvox/action@v1
  #     - name: Build
  #       run: pnpm --filter ember-command run build

  lint-js:
    name: lint:js
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: wyvox/action@v1
      - name: Build
        run: pnpm --filter ember-command run build
      - run: pnpm run -r --parallel --aggregate-output lint:js

  lint-hbs:
    name: lint:hbs
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: wyvox/action@v1
      - name: Build
        run: pnpm --filter ember-command run build
      - run: pnpm run -r --parallel --aggregate-output lint:hbs

  lint-types:
    name: lint:types
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: wyvox/action@v1
      - name: Build
        run: pnpm --filter ember-command run build
      - run: pnpm run -r --parallel --aggregate-output lint:types

  test-locked-deps:
    name: Locked Deps
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: wyvox/action@v1
      - name: Build package
        run: pnpm --filter ember-command build
      - name: Lint JS
        run: pnpm run -r --parallel --aggregate-output lint:js
      - name: Lint Types
        run: pnpm run -r --parallel --aggregate-output lint:types
      - name: Lint Handlebars
        run: pnpm run -r --parallel --aggregate-output lint:hbs
      - name: Tests
        run: pnpm run -r --parallel --aggregate-output test

  test-floating-deps:
    name: Floating Deps
    runs-on: ubuntu-lates
    steps:
      - name: Setup
        uses: wyvox/action@v1
        with:
          pnpm-args: --no-frozen-lockfile
      - name: Build package
        run: pnpm --filter ember-command build
      - name: Lint JS
        run: pnpm run -r --parallel --aggregate-output lint:js
      - name: Lint Types
        run: pnpm run -r --parallel --aggregate-output lint:types
      - name: Lint Handlebars
        run: pnpm run -r --parallel --aggregate-output lint:hbs
      - name: Tests
        run: pnpm run -r --parallel --aggregate-output test

  # test-try:
  #   name: Ember Try
  #   runs-on: ubuntu-20.04
  #   needs: [test-locked-deps]
  #   strategy:
  #     matrix:
  #       scenario:
  #         - ember-lts-3.20
  #         - ember-lts-3.24
  #         - ember-4.0.0
  #         - ember-release
  #         - ember-beta
  #         - ember-canary
  #         - embroider-safe
  #         - embroider-optimized
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Install Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #     - name: Install Dependencies
  #       run: yarn install --frozen-lockfile
  #     - name: Try Scenario
  #       run: yarn ember try:one ${{ matrix.scenario }}
